influxdb:
      kind: linux
      image: influxdb:2.7
      env:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: admin
        DOCKER_INFLUXDB_INIT_PASSWORD: labpassword123
        DOCKER_INFLUXDB_INIT_ORG: lab
        DOCKER_INFLUXDB_INIT_BUCKET: mdt
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
      ports: [ "8086:8086" ]

    grafana:
      kind: linux
      image: grafana/grafana:latest
      env:
        GF_SECURITY_ADMIN_PASSWORD: labpassword123
        GF_AUTH_ANONYMOUS_ENABLED: "true"
      ports: [ "3000:3000" ]
