---
- name: "PLAY 1 - ISSUE RUN COMMAND"
  hosts: "amers-cpe"
  gather_facts: "no"
  connection: "ansible.netcommon.network_cli"
  
  tasks:
  - name: "TASK1 - SHOW SNMP CONFIG"
    ios_command:
      commands:
        - "show run"


  #- name: "TASK 2 - DEPLOY SNMP COMMANDS"
  #  cisco.ios.ios_config:
   #   commands:
   #     - "snmp-server chassis-id {{ inventory_hostname }}""