[amers-cpe]
172.16.200.201 #ntp_server=2.2.2.2 #Host Variable
172.16.200.202

[amers-dc]
nxos-spine1
nxos-spine2

[amers:children] #Nested Groups
amers-cpe
amers-dc

[amers:vars] #Group Variables
ntp_server = 1.1.1.1


[emea-cpe]
vmx1
vmx2

[emea-dc]
eos-spine1
eos-spine2

[webservers]
www[01:50].example.com #Targets range of hosts
www[01:50:2].example.com #Stride of hosts, counts every second host (1, 3, 5)

[databases]
db-[a:f].example.com #Alphabetic ranges

[all:vars] #Default All group with assigned variable
syslog_server=192.168.1.0

[iosxe]
amers-cpe

[iosxe:vars]
ansible_network_os=ios